### ISSUE TITLE
Add TVS-473e to list

### ISSUE THREAD

**Issue by ricostuart** [WtfJoke/EmbyQNAPRepository#5]
Can this unit be added to the system to allow me to be able to use the repository on the device? I've set it all up but only comes up blank.

Thanks

**Comment by WtfJoke** [comment]
Hi @ricostuart 
I happily would add it, however the problem is that I need a platformId and the cpu architecture of that NAS and I am unaware of a method to determine/lookup the platformId.

Can you tell me which emby (cpu architecture) downloadlink you use?
Then I can try to guess the platform id and you can verify it if it works :)

**Comment by ricostuart** [comment]
Thanks mate. It's a AMD R7 RX-421BD which is a x64 CPU. So I just get the normal x86/x64 download. Thank you, Patrick
-------- Original message --------From: Manuel ***@***.***> Date: 09/02/2024  8:22 pm  (GMT+00:00) To: WtfJoke/EmbyQNAPRepository ***@***.***> Cc: ricostuart ***@***.***>, Mention ***@***.***> Subject: Re: [WtfJoke/EmbyQNAPRepository] Add TVS-473e to list (Issue #5) 
Hi @ricostuart
I happily would add it, however the problem is that I need a platformId and the cpu architecture of that NAS and I am unaware of a method to determine/lookup the platformId.
Can you tell me which emby (cpu architecture) downloadlink you use?
Then I can try to guess the platform id and you can verify it if it works :)

**Comment by WtfJoke** [comment]
Hey Patrick, please check if it now shows up (I hope so) and let me know. Thanks!

**Comment by ricostuart** [comment]
> Hey Patrick, please check if it now shows up (I hope so) and let me know. Thanks!

Just tested now and it works a treat! Your a star!
