### ISSUE TITLE
Add Missing QNAP Model TVS-873

### ISSUE THREAD

**Issue by jrdrake4** [WtfJoke/EmbyQNAPRepository#6]
Please add the TVS-873 Platform which uses the [Intel/AMD 64-bit]

(https://github.com/MediaBrowser/Emby.Releases/releases/download/4.8.10.0/emby-server-qnap_4.8.10.0_x86_64.qpkg)

Thank you

**Comment by WtfJoke** [comment]
Hey @jrdrake4 

Thanks for suggesting a new model and including the architecture.
I've added the model. However since the model name is usually just guessing, please test it and please give me feedback if it worked. 

Thank you!

**Comment by WtfJoke** [comment]
Since I havent heard from you I assume its working and close this one. If it doesnt work, feel free to reopen this issue or create a new one :)
